# Generated by Django 5.2.7 on 2025-10-30 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='data_acquisto',
            field=models.DateField(blank=True, help_text='Quando è stato acquistato il libro', null=True, verbose_name='Data di acquisto'),
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='numero_pagine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='prezzo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prezzo del libro in euro', max_digits=6, null=True, verbose_name='Prezzo (€)'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libri', to='libri.autore'),
        ),
    ]
