# Generated by Django 5.2.7 on 2025-10-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0002_autore_libro_data_acquisto_libro_isbn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='categorie',
            field=models.ManyToManyField(blank=True, related_name='libri', to='libri.categoria'),
        ),
    ]
