# Generated by Django 5.2.7 on 2025-10-31 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0004_recensione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='copertina',
            field=models.ImageField(blank=True, null=True, upload_to='copertine/'),
        ),
        migrations.AddField(
            model_name='recensione',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
